### ISSUE TITLE
Slurp not working on single fields?

### ISSUE THREAD

**Issue by malmaud** [one-more-minute/MacroTools.jl#2]
I'm trying to get all the fields in a type with 
```julia
@match e begin
type typename_
fields__
end -> (typename, fields)
```

which works as expected if 
```julia
e=quote
type T
x
y
end
end
```

but doesn't match if

```julia
e=quote
type T
x
end
end
```

**Comment by one-more-minute** [comment]
This should work fine on v0.1.0, are you definitely up to date?

**Comment by malmaud** [comment]
I'm definitely not up to date. Works fine now, thanks.
